language: node_js 
node_js: 
  - "stable"
cache:
  directories:
    - "server/node_modules"


env:
  global:
    -CODECLIMATE_REPO_TOKEN = 844a1b3370033c705944393c4d494f72a803b5b33d56b58c7599ceb8aec65b4e
before_install : 
 - cd server

install: 
  -npm install
script:
  npm run test

after_success:
  -npm run coverage
  -npm run coveralls
